### ISSUE TITLE
Kicad/ Eagle files

### ISSUE THREAD

**Issue by samuk** [ThBreuer/OpenRoboticBoard#1]
This looks interesting could you upload your EDA files so I can have a better look please?

**Comment by ThBreuer** [comment]
Thank you for your interesst! Sorry, but we don't have other formats than 'Target', neither Eagle nor KiCAD. For your information, I added a PDF with schematics and layout. Actually we work on a new version, which will be a little smaler.

**Comment by samuk** [comment]
Thanks. It looks like you might be able to export as Eagle? https://server.ibfriedrich.com/wiki/ibfwikien/index.php?title=Convert_TARGET_3001!_to_Eagle

**Comment by ThBreuer** [comment]
Sorry, I can't export to Eagle altough Target has an export function, but it doesn't work with my project.
The Motor-Bridge Cape is a very nice board, but not sufficiant because I need 4 motor encoder inputs and ADC/UART/I2C on each of 4 sensor inputs. In this sense Motor Bridge Cape is not similar.
